# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
  - step:
      name: Build & Install with NPM
      caches:
      - node
      script:
      - npm install
      - zip -r /tmp/my-app.zip *

  - step:
      name: Upload to S3
      image: atlassian/pipelines-awscli
      script:
      - aws --region $AWS_DEFAULT_REGION deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/my-app.zip --ignore-hidden-files



  - step:
      trigger: manual
      name: Deploy to AWS
      image: atlassian/pipelines-awscli
      script:
      - aws --region $AWS_DEFAULT_REGION deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/my-app.zip --ignore-hidden-files


